/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package excOne;
import java.util.Scanner;

public class App {
    static Scanner sc = new Scanner(System.in); 
    static Calculator calc = new Calculator();
    
    
    public static void main(String[] args) {
        Scanner sc = new Scanner(System.in); 
        Calculator calc = new Calculator();
    
       
        int inputOne, inputTwo;
        String operator;
        
        System.out.println("Digite o primeiro valor: ");
        inputOne = sc.nextInt();
        
        System.out.println("Digite o segundo valor: ");
        inputTwo = sc.nextInt();
        
        sc.nextLine();
        System.out.println("Digite o simbolo do operador: exc: / , + , - , *:  ");
        operator = sc.nextLine();
        
        calc.runCalculator(operator, inputOne, inputTwo);
        
    }
}
