/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package meuSegundoProjetoJava;
// importando a classe Scanner
import java.util.Scanner;

public class App {
 
 // Criando um objeto scanner para ler a entrada pelo terminal 
 static Scanner sc = new Scanner(System.in);
  
 public static void main(String[] args) {
//     Frase myPhrse = new Frase();
//     myPhrse.printPhrse(myPhrse.returnFrase());
//       
//        
//      Vehicle vehicle = new Vehicle(4, "VolskVagen", 10000);
//      vehicle.run();
//      
//      Car myCar = new Car("Ford", 4000, 2);
//      myCar.maneuver();

        // Declarando duas variaveis inteiras para armazenar os dados dado pelo terminal 
        int number1, number2;

        //solicitando que o usuario digite um numero inteiro
        System.out.println("Digite o primero número: ");
        // atribuindo o valor do terminal a variavel number1 
        number1 = sc.nextInt();// Lê o proximo inteiro digitado ao terminal
        
        
        sc.nextLine();
        
        
        System.out.println("Digite seu nome: ");
        String name = sc.nextLine();
        
        
        System.out.println(" Digite outro número: ");
        number2 = sc.nextInt();
        
        System.out.println(name + ", O resultado é " + (number1 + number2));
        
        sc.close();
    }
}
