/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package meuProjetoJava;
import java.util.Scanner;




public class App {
    
   
    
    public void promotion(Product prod) {
        System.out.println("o produto " + prod.getName() + " está em promoção "
        + "pro apenas " + prod.getPrice());
    }
    
    
      
    public static void main(String[] args) {
    int age;    
    Scanner myScanner = new Scanner(System.in);
    
    
    System.out.println("Qual o seu nome: ");
    String name = myScanner.nextLine();
    
    System.out.println("Digite sua idade: ");
    age = myScanner.nextInt();
    myScanner.nextLine();
    
    System.out.println("Qual o seu sobrenome: ");
    String sobreNome = myScanner.nextLine();
    
    System.out.println("Olá " + name +  " " + sobreNome + " ");

    
    System.out.println("sua idade: " + age);
    
//    int number1, number2; 
//    
//    System.out.println("Digite um numero: ");
//    number1 = myScanner.nextInt();
//    
//    System.out.println("Digite outro número: ");
//    number2 = myScanner.nextInt();
//    
//    System.out.println("Resultado é " + (number1 + number2));
//    myScanner.close();
//        
//        Teste myTest = new Teste();
//        myTest.sum(5, 5);
        
//     
//     int number = 1;
//       
//     String result = (number % 2 == 0) ? "PAR" : "IMPAR";
//     System.out.println("O Seu numeo é " + result);
     
     
//     int voltas = 0;
//     
//     while(voltas < 10) {
//         
//         System.out.println("Você já deu " + voltas);
//         voltas++;
//     }
//     
//     for (int i =0; i < 10; i++)  {
//         System.out.print(i);
//     }
       
      int[] orderList = new int[6];
      orderList[0] = 4;
      orderList[1] = 6;
      orderList[2] = 9;
      orderList[3] = 10;
      orderList[4] = 30;
      orderList[5] = 70;
      
      queryBinary(orderList, 70);
      
      
//      Person p1 = new Person("vitinho", 22);;
//      p1.walk();
//      Product newProduct = new Product("Book", 50);
//      System.out.println(newProduct.getName());
//      Eletronic newEl = new Eletronic("TV", 3009.993, 230);
//      System.out.println(newEl.getPrice());
//      
//      App myApp = new App();
//      myApp.promotion(newEl);
//   
//     int age = 17;;
//     double heigth = 1.80;
//     String name = "Arthur Tavares";
//     char initialLetter = 'A';
//     boolean isStudent = true; 
//     Integer note = 100; 
//     
//     
//     int dayOfWeek = 5;
//     
//     switch(dayOfWeek) {
//         case 1:
//             System.out.println("Domingo");
//             break;
//         case 2:
//             System.out.println("Segunda-feira");
//             break;
//         case 3:
//             System.out.println("Terça-feira");
//             break;
//         case 4:
//             System.out.println("Quarta-feira");
//             break;
//         case 5:
//             System.out.println("Quinta-feira");
//             break;
//         case 6:
//             System.out.println("Sexta-feira");
//             break;
//         case 7:
//             System.out.println("Sabado");
//             break;
//             
//         default:
//             System.out.println("Não sei que dia é mano");
//             break;
//             
//     }
     
    }
    

    
    
    public static int queryBinary(int[] list, int value) {
      int baixo = 0;
      int alto = list.length - 1 ; 
      
      while(baixo <= alto) {
          int meio =  Math.round((baixo + alto) / 2); 
          int chute = list[meio];
          
          if(chute == value) {
              System.out.println(meio);
              return chute;
          } 
          
          if(chute < value) {
              baixo = meio + 1;
          }
          
          else {
              alto = meio - 1;
          }
          
          
          
      }
      
      
      return 400;
        
    }
   
}

